# docker-compose.yaml  (Compose v2 — без поля version)

networks:
  client-net:
    name: ${CLIENT_NAME}-net
    driver: bridge

services:
  # === Nextcloud (official, Apache) ===
  nextcloud:
    image: nextcloud:${NC_APACHE_TAG}      # напр. 27-apache
    container_name: ${CLIENT_NAME}-nextcloud
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      TZ: ${TZ}
      # MariaDB
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Admin
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      # храним всё в html (конфиг, apps, data и т.п.) — просто и надёжно для теста
      - ${DOCKER_DATA}/${CLIENT_NAME}/nextcloud/html:/var/www/html
    restart: unless-stopped
    networks: [client-net]

  # === MariaDB ===
  db:
    image: mariadb:10.11
    container_name: ${CLIENT_NAME}-mariadb
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DOCKER_DATA}/${CLIENT_NAME}/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [client-net]

  # === ONLYOFFICE Document Server (включай профилем onlyoffice) ===
  onlyoffice:
    image: onlyoffice/documentserver:${ONLYOFFICE_TAG}
    container_name: ${CLIENT_NAME}-onlyoffice
    environment:
      TZ: ${TZ}
      JWT_ENABLED: "true"
      JWT_SECRET: ${ONLYOFFICE_JWT}
      JWT_HEADER: Authorization
    ports:
      - "${ONLYOFFICE_PORT}:80"
    restart: unless-stopped
    networks: [client-net]
    profiles: ["onlyoffice"]

  # === Collabora CODE (включай профилем collabora) ===
  collabora:
    image: collabora/code:${COLLABORA_TAG}
    container_name: ${CLIENT_NAME}-collabora
    cap_add: [MKNOD]
    environment:
      TZ: ${TZ}
      username: ${COLLABORA_USER}
      password: ${COLLABORA_PASS}
      DONT_GEN_SSL_CERT: "true"                  # без TLS для локалки
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
      # Разрешить запросы от домена твоего nextcloud (регэксп)
      domain: ${NC_DOMAIN_REGEX}
    ports:
      - "${COLLABORA_PORT}:9980"
    restart: unless-stopped
    networks: [client-net]
    profiles: ["collabora"]
